version: '3.8'

services:
  bohorquezailabs:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: bohorquezailabs
    ports:
      - "8501:8501"
    volumes:
      - ./pages:/app/pages
      - ./assets:/app/assets
      - ./mlruns:/app/mlruns
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
